# Generated by Django 6.0.7 on 2026-09-06 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0055_userprofile_language"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apitoken",
            options={"verbose_name": "API token", "verbose_name_plural": "API tokens"},
        ),
        migrations.AlterModelOptions(
            name="bookmark",
            options={"verbose_name": "bookmark", "verbose_name_plural": "bookmarks"},
        ),
        migrations.AlterModelOptions(
            name="bookmarkasset",
            options={
                "verbose_name": "bookmark asset",
                "verbose_name_plural": "bookmark assets",
            },
        ),
        migrations.AlterModelOptions(
            name="bookmarkbundle",
            options={"verbose_name": "bundle", "verbose_name_plural": "bundles"},
        ),
        migrations.AlterModelOptions(
            name="feedtoken",
            options={
                "verbose_name": "feed token",
                "verbose_name_plural": "feed tokens",
            },
        ),
        migrations.AlterModelOptions(
            name="globalsettings",
            options={
                "verbose_name": "global settings",
                "verbose_name_plural": "global settings",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "tag", "verbose_name_plural": "tags"},
        ),
        migrations.AlterModelOptions(
            name="toast",
            options={"verbose_name": "toast", "verbose_name_plural": "toasts"},
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "user profile",
                "verbose_name_plural": "user profiles",
            },
        ),
    ]
